### ISSUE TITLE
Ejercicios dentro de un proyecto, no de un wiki

### ISSUE THREAD

**Issue by JJ** [PSanchezR/Ejercicios-#1]
Es más fácil para que podamos corregirlos. Puedes copiar el MarkDown directamente a un ejercicio. Aparte, hay cosas incompletas al menos en los del tema de virtualización.

**Comment by PSanchezR** [comment]
Si JJ esta semana es que tengo dos examenes y varios trabajos que entregar pero la semana que viene voy a reestructurar mis ejercicios, crearé un proyecto para ellos exclusivamente, haré un wiki por tema con los ejercicios de cada uno y terminaré los ejercicios que me faltan.

**Comment by JJ** [comment]
OK, cuando puedas, no te preocupes. Si quieres hazlo sólo para los nuevos.

**Comment by PSanchezR** [comment]
Muchisimas gracias por la flexibilidad, en cuanto tenga todo reestructurado, le aviso por un issue.
